# Generated by Django 4.2.27 on 2026-01-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О нашей компании', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('mission_title', models.CharField(default='Наша миссия и видение', max_length=200)),
                ('mission_text', models.TextField(blank=True)),
                ('team_title', models.CharField(default='Наша команда', max_length=200)),
                ('cta_title', models.CharField(default='Готовы найти нужные запчасти?', max_length=200)),
                ('cta_text', models.CharField(blank=True, max_length=300)),
                ('cta_button_text', models.CharField(default='Перейти в каталог', max_length=80)),
                ('cta_button_url', models.CharField(default='/catalog/', max_length=200)),
                ('cta_second_button_text', models.CharField(default='Связаться с нами', max_length=80)),
                ('cta_second_button_url', models.CharField(default='/contacts/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'О нас (страница)',
                'verbose_name_plural': 'О нас (страница)',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('bio', models.CharField(blank=True, max_length=400)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='shop.aboutpage')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Например: 5000+', max_length=40)),
                ('label', models.CharField(help_text='Например: Деталей в наличии', max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='shop.aboutpage')),
            ],
            options={
                'verbose_name': 'О нас: показатель',
                'verbose_name_plural': 'О нас: показатели',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Иконка FontAwesome, например: fa-solid fa-badge-check', max_length=40)),
                ('color', models.CharField(default='blue', help_text='blue/green/purple (для цвета бейджа)', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.aboutpage')),
            ],
            options={
                'verbose_name': 'О нас: преимущество',
                'verbose_name_plural': 'О нас: преимущества',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
